build:
  - npm install
  - npm run build

start:
  - npm start

env:
  - key: NODE_ENV
    value: production
  - key: FRONTEND_URL
    fromService:
      type: web
      name: gj-camp-frontend
      property: url
